name: Deploy-AWS-S3

on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      S3_ENDPOINT_URL: ${{secrets.S3_ENDPOINT_URL}}
      S3_DESTINATION: ${{secrets.S3_DESTINATION}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Setup Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://${{secrets.ACCESS_TOKEN}}@github.com/MailRuCloudSolutions/mcs-docs-theme.git

      - name: Build the documentation
        run: python -m sphinx doc output -c .

      - name: Remove the documentation from the current AWS S3 directory
        run: aws s3 rm ${S3_DESTINATION}/help/${GITHUB_REF#refs/heads/} --endpoint-url=${S3_ENDPOINT_URL} --recursive

      - name: Copy the documentation to AWS S3 directory
        run: aws s3 cp output ${S3_DESTINATION}/help/${GITHUB_REF#refs/heads/} --endpoint-url=${S3_ENDPOINT_URL} --recursive